[package]
name = "moka_rust"
version = "0.1.0"
authors = ["Louis Capitanchik <ljcapitanio@gmail.com>"]

[lib]
name="mokafunc"

[[bin]]
name="moka"

[dependencies]
docopt = "0.6"
rustc-serialize = "0.3"
